version: 0.1.{build}
image: Ubuntu
environment:
  NugetApiKey: 6e01b1be-4aa2-445d-bd6e-036fa77e600c
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: false
build_script:
- ps: ./build.ps1
deploy_script:
- ps: ./build.ps1 Pack -NugetVersionPrefix 0.1.$env:APPVEYOR_BUILD_NUMBER  -NugetVersionSuffix alpha
- ps: ./build.ps1 Push --NugetApiUrl "https://www.myget.org/F/phyros/api/v2/package" --NugetApiKey $env:NugetApiKey