version: '1.0.{build}'
image: Visual Studio 2019

branches:
  only:
  - master

environment:
  BaseVersion: 0.1
  NugetVersion: "0.1.$(APPVEYOR_BUILD_NUMBER)"

assembly_info:
  patch: true
  file: 'src\**\AssemblyInfo.*'
  assembly_version: "$(BaseVersion)"
  assembly_file_version: "$(BaseVersion)"
  assembly_informational_version: "$(NugetVersion)"

nuget:
  project_feed: true
  disable_publish_on_pr: false

configuration: Release

before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Phyros.Athena.Model.WorkflowProcess/Phyros.Athena.Model.WorkflowProcess.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./src/Phyros.Athena.Model.WorkflowProcess/Phyros.Athena.Model.WorkflowProcess.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: './src/Phyros.Athena.Model.WorkflowProcess/bin/Release'
   name: NuGet